# Generated by Django 3.2 on 2022-02-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='عنوان')),
                ('credit', models.PositiveSmallIntegerField()),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'db_table': 'lesson',
            },
        ),
    ]
