# Generated by Django 3.2 on 2022-02-05 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_lessonmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.lessonmodel', verbose_name='کلاسهای دروس')),
                ('student', models.ManyToManyField(related_name='lesson_list', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_list', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'db_table': 'user_class',
            },
        ),
    ]
