# Generated by Django 3.2 on 2022-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_classmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
