# Generated by Django 3.2 on 2022-02-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_classmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
