# Generated by Django 3.2 on 2022-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_classmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
